# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.CharField(help_text='مثلاً: plans_page, calculator, home_hero', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
            ],
            options={
                'verbose_name': 'نية شراء (Lead)',
                'verbose_name_plural': 'نوايا الشراء (Leads)',
                'ordering': ['-created_at'],
            },
        ),
    ]
