# Generated by Django 6.1 on 2026-09-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('plans', '0004_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.discountcode', verbose_name='كود الخصم المستخدم'),
        ),
    ]
