# Generated by Django 6.1 on 2026-09-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_discount_code'),
        ('plans', '0005_alter_deliveryarea_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='الخطة'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source_page',
            field=models.CharField(help_text='مثلاً: plans_page, calculator, home_hero', max_length=100, verbose_name='صفحة المصدر'),
        ),
    ]
