# Generated by Django 6.1 on 2026-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name_ar', models.CharField(default='Low Calories Jordan | لو كالوريز', max_length=100)),
                ('brand_name_en', models.CharField(default='Low Calories Jordan', max_length=100)),
                ('tagline_ar', models.CharField(default='وجبات صحية محسوبة السعرات، توصلك لباب بيتك في عمّان', max_length=200)),
                ('tagline_en', models.CharField(default='Calorie-counted healthy meals, delivered in Amman', max_length=200)),
                ('whatsapp_number', models.CharField(default='962XXXXXXXXX', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/lowcalories_jor/')),
                ('app_store_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('google_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
