# Generated by Django 6.1 on 2026-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#F0791E', help_text='اللون البرتقالي الأساسي (أزرار، هيدر، تمييز)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#4C8C3C', help_text="اللون الأخضر (لوجو 'Low' بالخط اليدوي، تفاصيل ثانوية)", max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='soft_bg_color',
            field=models.CharField(default='#FDF1E1', help_text='لون الخلفية الكريمية الفاتحة (خلفيات السكاشن)', max_length=7),
        ),
    ]
