# Generated by Django 6.1 on 2026-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=5)),
                ('text_ar', models.TextField()),
                ('text_en', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تقييم عميل',
                'verbose_name_plural': 'تقييمات العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='رقم Meta/Facebook Pixel (بدون حروف). لو فاضي، ما رح ينحقن أي كود تتبع بالموقع.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_embed_code',
            field=models.TextField(blank=True, help_text='الصق هون كود الـ embed تبع أي خدمة تقييمات خارجية (ReputationHub، Elfsight، أو iframe تقييمات Google مباشرة). إذا تركته فاضي، الموقع بيعرض تلقائياً التقييمات اليدوية (Testimonials) بدلاً منه.'),
        ),
    ]
