# Generated by Django 6.1 on 2026-09-02 07:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testimonial_sitesettings_facebook_pixel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSiteSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('brand_name_ar', models.CharField(default='Low Calories Jordan | لو كالوريز', max_length=100)),
                ('brand_name_en', models.CharField(default='Low Calories Jordan', max_length=100)),
                ('tagline_ar', models.CharField(default='وجبات صحية محسوبة السعرات، توصلك لباب بيتك في عمّان', max_length=200)),
                ('tagline_en', models.CharField(default='Calorie-counted healthy meals, delivered in Amman', max_length=200)),
                ('whatsapp_number', models.CharField(default='962XXXXXXXXX', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/lowcalories_jor/')),
                ('app_store_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('google_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('reviews_embed_code', models.TextField(blank=True, help_text='الصق هون كود الـ embed تبع أي خدمة تقييمات خارجية (ReputationHub، Elfsight، أو iframe تقييمات Google مباشرة). إذا تركته فاضي، الموقع بيعرض تلقائياً التقييمات اليدوية (Testimonials) بدلاً منه.')),
                ('facebook_pixel_id', models.CharField(blank=True, help_text='رقم Meta/Facebook Pixel (بدون حروف). لو فاضي، ما رح ينحقن أي كود تتبع بالموقع.', max_length=30)),
                ('logo', models.TextField(blank=True, max_length=100)),
                ('primary_color', models.CharField(default='#F0791E', help_text='اللون البرتقالي الأساسي (أزرار، هيدر، تمييز)', max_length=7)),
                ('secondary_color', models.CharField(default='#4C8C3C', help_text="اللون الأخضر (لوجو 'Low' بالخط اليدوي، تفاصيل ثانوية)", max_length=7)),
                ('soft_bg_color', models.CharField(default='#FDF1E1', help_text='لون الخلفية الكريمية الفاتحة (خلفيات السكاشن)', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical إعدادات الموقع',
                'verbose_name_plural': 'historical إعدادات الموقع',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
