# Generated by Django 6.1 on 2026-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalsitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='consultation_duration_min',
            field=models.PositiveIntegerField(default=20, help_text='مدة جلسة الاستشارة بالدقائق (تظهر بصفحة الاستشارات).'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='consultation_price_jod',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر جلسة استشارة التغذية (د.أ). يُنسخ للحجز وقت إنشائه.', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consultation_duration_min',
            field=models.PositiveIntegerField(default=20, help_text='مدة جلسة الاستشارة بالدقائق (تظهر بصفحة الاستشارات).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consultation_price_jod',
            field=models.DecimalField(decimal_places=2, default=0, help_text='سعر جلسة استشارة التغذية (د.أ). يُنسخ للحجز وقت إنشائه.', max_digits=6),
        ),
    ]
