# Generated by Django 6.1 on 2026-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalsitesettings_consultation_duration_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('calories', 'سعرات محسوبة'), ('delivery', 'توصيل يومي'), ('variety', 'تنوّع المنيو'), ('fresh', 'طازج'), ('support', 'دعم ومتابعة')], default='calories', max_length=20, verbose_name='الأيقونة')),
                ('title_ar', models.CharField(max_length=80, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=80, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.CharField(max_length=180, verbose_name='الوصف (عربي)')),
                ('text_en', models.CharField(blank=True, max_length=180, verbose_name='الوصف (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'ميزة (ليش تختارنا)',
                'verbose_name_plural': 'مزايا (ليش تختارنا)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='hero_image',
            field=models.TextField(blank=True, help_text='صورة الـ Hero بالصفحة الرئيسية. لو فاضية، يظهر رسم توضيحي بألوان الهوية.', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='رابط سياسة الخصوصية (يظهر بالفوتر إذا معبّأ)'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='working_hours_ar',
            field=models.CharField(blank=True, help_text='مثال: يومياً ٩ ص – ٩ م (يظهر بالفوتر إذا معبّأ)', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='صورة الـ Hero بالصفحة الرئيسية. لو فاضية، يظهر رسم توضيحي بألوان الهوية.', upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_url',
            field=models.URLField(blank=True, help_text='رابط سياسة الخصوصية (يظهر بالفوتر إذا معبّأ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_ar',
            field=models.CharField(blank=True, help_text='مثال: يومياً ٩ ص – ٩ م (يظهر بالفوتر إذا معبّأ)', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='primary_color',
            field=models.CharField(default='#FD7B01', help_text='اللون البرتقالي الأساسي (أزرار، هيدر، تمييز)', max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='secondary_color',
            field=models.CharField(default='#00A850', help_text="اللون الأخضر (لوجو 'Low' بالخط اليدوي، تفاصيل ثانوية)", max_length=7),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='soft_bg_color',
            field=models.CharField(default='#FFF3E6', help_text='لون الخلفية الكريمية الفاتحة (خلفيات السكاشن)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#FD7B01', help_text='اللون البرتقالي الأساسي (أزرار، هيدر، تمييز)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#00A850', help_text="اللون الأخضر (لوجو 'Low' بالخط اليدوي، تفاصيل ثانوية)", max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='soft_bg_color',
            field=models.CharField(default='#FFF3E6', help_text='لون الخلفية الكريمية الفاتحة (خلفيات السكاشن)', max_length=7),
        ),
    ]
