# Generated by Django 6.1 on 2026-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitefeature_historicalsitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ar', models.CharField(max_length=200, verbose_name='السؤال (عربي)')),
                ('question_en', models.CharField(blank=True, max_length=200, verbose_name='السؤال (إنجليزي)')),
                ('answer_ar', models.TextField(verbose_name='الجواب (عربي)')),
                ('answer_en', models.TextField(blank=True, verbose_name='الجواب (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=60, verbose_name='النص (عربي)')),
                ('text_en', models.CharField(blank=True, max_length=60, verbose_name='النص (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'هدف (Hero)',
                'verbose_name_plural': 'أهداف الـ Hero المتغيّرة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=80, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=80, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.CharField(max_length=160, verbose_name='الوصف (عربي)')),
                ('text_en', models.CharField(blank=True, max_length=160, verbose_name='الوصف (إنجليزي)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'خطوة (كيف يعمل)',
                'verbose_name_plural': 'خطوات «كيف يعمل»',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='hero_stat_ar',
            field=models.CharField(blank=True, help_text='مثال: نوصّل يومياً داخل عمّان', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='hero_stat_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_ar',
            field=models.CharField(blank=True, help_text='مثال: نوصّل يومياً داخل عمّان', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='testimonials/', verbose_name='صورة العميل (اختياري)'),
        ),
    ]
