# Generated by Django 6.1 on 2026-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq_herogoal_howitworksstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='terms_url',
            field=models.URLField(blank=True, help_text='رابط الشروط والأحكام (يظهر بالفوتر إذا معبّأ)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_url',
            field=models.URLField(blank=True, help_text='رابط الشروط والأحكام (يظهر بالفوتر إذا معبّأ)'),
        ),
    ]
