# Generated by Django 6.1 on 2026-09-02 16:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicalsitesettings_terms_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='يظهر بالرابط: /policies/<slug>/ (مثال: privacy, terms).', max_length=60, unique=True, verbose_name='المعرّف بالرابط')),
                ('title_ar', models.CharField(max_length=140, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=140, verbose_name='العنوان (إنجليزي)')),
                ('is_published', models.BooleanField(default=False, help_text='ما تنشرها إلا بعد ما يتأكد المحتوى القانوني. غير منشورة = ما إلها رابط بالفوتر ولا صفحة (404).', verbose_name='منشورة')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='تظهر بروابط الفوتر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='رقم النسخة (اختياري)')),
                ('last_updated', models.DateField(blank=True, help_text="التاريخ اللي يظهر بأعلى الصفحة ('آخر تحديث: ...').", null=True, verbose_name='آخر تحديث')),
                ('meta_description_ar', models.CharField(blank=True, max_length=180, verbose_name='وصف SEO (عربي)')),
                ('meta_description_en', models.CharField(blank=True, max_length=180, verbose_name='وصف SEO (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سياسة / صفحة قانونية',
                'verbose_name_plural': 'السياسات والصفحات القانونية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='اسم المستخدم بدون @ (اختياري — للعرض النصي فقط).', max_length=60),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='location_ar',
            field=models.CharField(blank=True, default='عمّان، الأردن', help_text='الموقع كما يظهر بالفوتر وصفحات السياسات (مثال: عمّان، الأردن).', max_length=160),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='location_en',
            field=models.CharField(blank=True, default='Amman, Jordan', max_length=160),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='بريد الدعم/التواصل (يظهر بصفحات السياسات إذا معبّأ).', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='whatsapp_default_message_ar',
            field=models.CharField(blank=True, help_text='رسالة مبدئية تُملأ في واتساب عند الضغط على أي زر عام (اختياري).', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='whatsapp_default_message_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='whatsapp_display',
            field=models.CharField(blank=True, help_text='الصيغة المعروضة للزوار (مثال: +962 79 123 4567). لو فاضي نعرض الرقم المنسّق آلياً من whatsapp_number.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='اسم المستخدم بدون @ (اختياري — للعرض النصي فقط).', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_ar',
            field=models.CharField(blank=True, default='عمّان، الأردن', help_text='الموقع كما يظهر بالفوتر وصفحات السياسات (مثال: عمّان، الأردن).', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, default='Amman, Jordan', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='بريد الدعم/التواصل (يظهر بصفحات السياسات إذا معبّأ).', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_default_message_ar',
            field=models.CharField(blank=True, help_text='رسالة مبدئية تُملأ في واتساب عند الضغط على أي زر عام (اختياري).', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_default_message_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_display',
            field=models.CharField(blank=True, help_text='الصيغة المعروضة للزوار (مثال: +962 79 123 4567). لو فاضي نعرض الرقم المنسّق آلياً من whatsapp_number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/lowcalories_jor/', help_text='رابط صفحة إنستغرام كامل. اتركه فاضي = يختفي أيقونة إنستغرام.'),
        ),
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='رقم واتساب برمز الدولة (مثال: 962791234567 أو +962 79 123 4567). يُنظَّف آلياً لتوليد رابط wa.me. اتركه فاضي = تختفي كل عناصر واتساب.', max_length=25),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/lowcalories_jor/', help_text='رابط صفحة إنستغرام كامل. اتركه فاضي = يختفي أيقونة إنستغرام.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='رقم واتساب برمز الدولة (مثال: 962791234567 أو +962 79 123 4567). يُنظَّف آلياً لتوليد رابط wa.me. اتركه فاضي = تختفي كل عناصر واتساب.', max_length=25),
        ),
        migrations.CreateModel(
            name='HistoricalPolicy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('slug', models.SlugField(help_text='يظهر بالرابط: /policies/<slug>/ (مثال: privacy, terms).', max_length=60, verbose_name='المعرّف بالرابط')),
                ('title_ar', models.CharField(max_length=140, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=140, verbose_name='العنوان (إنجليزي)')),
                ('is_published', models.BooleanField(default=False, help_text='ما تنشرها إلا بعد ما يتأكد المحتوى القانوني. غير منشورة = ما إلها رابط بالفوتر ولا صفحة (404).', verbose_name='منشورة')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='تظهر بروابط الفوتر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='رقم النسخة (اختياري)')),
                ('last_updated', models.DateField(blank=True, help_text="التاريخ اللي يظهر بأعلى الصفحة ('آخر تحديث: ...').", null=True, verbose_name='آخر تحديث')),
                ('meta_description_ar', models.CharField(blank=True, max_length=180, verbose_name='وصف SEO (عربي)')),
                ('meta_description_en', models.CharField(blank=True, max_length=180, verbose_name='وصف SEO (إنجليزي)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical سياسة / صفحة قانونية',
                'verbose_name_plural': 'historical السياسات والصفحات القانونية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('heading_ar', models.CharField(blank=True, max_length=160, verbose_name='عنوان القسم (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=160, verbose_name='عنوان القسم (إنجليزي)')),
                ('body_ar', models.TextField(blank=True, help_text='افصل كل فقرة بسطر فارغ.', verbose_name='الفقرات (عربي)')),
                ('body_en', models.TextField(blank=True, verbose_name='الفقرات (إنجليزي)')),
                ('list_type', models.CharField(choices=[('none', 'بدون قائمة'), ('bullet', 'قائمة نقطية'), ('number', 'قائمة مرقّمة')], default='none', max_length=10, verbose_name='نوع القائمة')),
                ('list_items_ar', models.TextField(blank=True, help_text='عنصر واحد بكل سطر.', verbose_name='عناصر القائمة (عربي)')),
                ('list_items_en', models.TextField(blank=True, verbose_name='عناصر القائمة (إنجليزي)')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.policy')),
            ],
            options={
                'verbose_name': 'قسم سياسة',
                'verbose_name_plural': 'أقسام السياسة',
                'ordering': ['order', 'id'],
            },
        ),
    ]
