# Generated by Django 6.1 on 2026-09-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_policy_historicalsitesettings_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='hero_image_focus',
            field=models.CharField(blank=True, default='center center', help_text='نقطة تركيز قص صورة الـ Hero (object-position)، مثال: center center أو 60% 40%.', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو mp4 للـ Hero (اختياري). لو معبّأ يُعرض بدل الصورة (صامت، تلقائي، مع احترام تفضيل تقليل الحركة). صورة الـ Hero تصير poster.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image_focus',
            field=models.CharField(blank=True, default='center center', help_text='نقطة تركيز قص صورة الـ Hero (object-position)، مثال: center center أو 60% 40%.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو mp4 للـ Hero (اختياري). لو معبّأ يُعرض بدل الصورة (صامت، تلقائي، مع احترام تفضيل تقليل الحركة). صورة الـ Hero تصير poster.'),
        ),
    ]
