# Generated by Django 6.1 on 2026-09-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalsitesettings_hero_image_focus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category_ar',
            field=models.CharField(blank=True, help_text='اختياري — للتنظيم المستقبلي (خطط، وجبات، توصيل...). ما يظهر كفلتر إلا لو احتجناه.', max_length=60, verbose_name='التصنيف (عربي)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='التصنيف (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='show_on_homepage',
            field=models.BooleanField(default=True, verbose_name='يظهر بمقتطف الصفحة الرئيسية'),
        ),
    ]
