# Generated by Django 6.1 on 2026-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_faq_category_ar_faq_category_en_faq_show_on_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'تقييم عميل', 'verbose_name_plural': 'تقييمات العملاء'},
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='image',
            field=models.ImageField(blank=True, upload_to='how/', verbose_name='صورة الخطة'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='image_focus',
            field=models.CharField(blank=True, default='center center', help_text='object-position، مثال: center center أو 50% 30%.', max_length=30, verbose_name='نقطة تركيز القص'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='مميّز (يظهر بالصفحة الرئيسية)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location_ar',
            field=models.CharField(blank=True, max_length=80, verbose_name='الموقع (اختياري)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='الموقع (إنجليزي)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='plan_label_ar',
            field=models.CharField(blank=True, max_length=80, verbose_name='الخطة (اختياري)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='plan_label_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='الخطة (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='text_ar',
            field=models.CharField(max_length=200, verbose_name='الوصف (عربي)'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الوصف (إنجليزي)'),
        ),
    ]
