# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'منطقة توصيل',
                'verbose_name_plural': 'مناطق التوصيل',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(help_text='مثال: 20 / 24 / 26')),
                ('meals_per_day', models.PositiveIntegerField(default=1)),
                ('price_jod', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_popular', models.BooleanField(default=False, help_text="يظهر عليها وسم 'الأكثر شعبية'")),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtype')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['days', 'price_jod'],
            },
        ),
    ]
