# Generated by Django 6.1 on 2026-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_weeklymenu_is_active'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryarea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['days'], name='plans_plan_days_d65bf1_idx'),
        ),
    ]
