# Generated by Django 6.1 on 2026-09-02 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_historicaldeliveryarea_historicalplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: WELCOME15', max_length=30, unique=True, verbose_name='الكود')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الخصم %')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('valid_until', models.DateField(blank=True, help_text='فاضي = بدون تاريخ انتهاء', null=True, verbose_name='صالح حتى')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='فاضي = بدون حد', null=True, verbose_name='أقصى عدد استخدامات')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد الاستخدامات')),
            ],
            options={
                'verbose_name': 'كود خصم',
                'verbose_name_plural': 'أكواد الخصم',
            },
        ),
    ]
