# Generated by Django 6.1 on 2026-09-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_historicalmenuitem_calories_and_more'),
        ('plans', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryarea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='name_ar',
            field=models.CharField(max_length=80, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='deliveryarea',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='historicaldeliveryarea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='مفعّلة'),
        ),
        migrations.AlterField(
            model_name='historicaldeliveryarea',
            name='name_ar',
            field=models.CharField(max_length=80, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='historicaldeliveryarea',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='days',
            field=models.PositiveIntegerField(help_text='مثال: 20 / 24 / 26', verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="يظهر عليها وسم 'الأكثر شعبية'", verbose_name='الأكثر طلباً'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='meal_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='menu.mealtype', verbose_name='نوع الوجبة'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='meals_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='وجبات باليوم'),
        ),
        migrations.AlterField(
            model_name='historicalplan',
            name='price_jod',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر (د.أ)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='days',
            field=models.PositiveIntegerField(help_text='مثال: 20 / 24 / 26', verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="يظهر عليها وسم 'الأكثر شعبية'", verbose_name='الأكثر طلباً'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtype', verbose_name='نوع الوجبة'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='meals_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='وجبات باليوم'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_jod',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر (د.أ)'),
        ),
    ]
