# Generated by Django 6.1 on 2026-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_deliveryarea_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='image',
            field=models.TextField(blank=True, help_text='صورة خاصة بهذه الخطة تحديداً. لو فاضية نستخدم صورة نوع الوجبة.', max_length=100, null=True, verbose_name='صورة خاصة بالخطة'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة خاصة بهذه الخطة تحديداً. لو فاضية نستخدم صورة نوع الوجبة.', null=True, upload_to='plans/', verbose_name='صورة خاصة بالخطة'),
        ),
    ]
