# Generated by Django 6.1 on 2026-09-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(max_length=120, verbose_name='اسم صاحب الكود')),
                ('referrer_phone', models.CharField(max_length=20, unique=True, verbose_name='رقم هاتفه')),
                ('code', models.SlugField(allow_unicode=True, blank=True, max_length=24, unique=True, verbose_name='الكود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كود إحالة',
                'verbose_name_plural': 'أكواد الإحالة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_name', models.CharField(max_length=120, verbose_name='اسم الصديق')),
                ('referred_phone', models.CharField(max_length=20, verbose_name='رقم هاتف الصديق')),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('redeemed', 'تم الاستبدال'), ('expired', 'منتهي')], default='pending', max_length=12, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستبدال')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralcode', verbose_name='كود الإحالة')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
