# Generated by Django 6.1 on 2026-09-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_historicalmenuitem_historicalweeklymenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='اسم الشركة')),
                ('contact_person', models.CharField(max_length=120, verbose_name='الشخص المسؤول')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم التواصل')),
                ('employee_count', models.PositiveIntegerField(verbose_name='عدد الموظفين التقريبي')),
                ('delivery_location', models.CharField(max_length=200, verbose_name='موقع التوصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب عرض سعر شركة',
                'verbose_name_plural': 'طلبات عروض أسعار الشركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_employees', models.PositiveIntegerField(verbose_name='أقل عدد موظفين')),
                ('max_employees', models.PositiveIntegerField(blank=True, help_text='اتركه فاضي للشريحة المفتوحة (مثال: 50+).', null=True, verbose_name='أكثر عدد موظفين')),
                ('price_per_employee_jod', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سعر الموظف (د.أ)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtype', verbose_name='نوع الوجبة')),
            ],
            options={
                'verbose_name': 'خطة شركات',
                'verbose_name_plural': 'خطط الشركات',
                'ordering': ['min_employees'],
            },
        ),
    ]
