# Generated by Django 6.1 on 2026-09-02 07:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0003_historicaldeliveryarea_historicalplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='بصيغة دولية بدون + (مثال: 962795551234)', max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('access_code', models.CharField(blank=True, help_text='يُنشأ تلقائياً. شاركه مع العميل ليدخل بوابته (بديل مؤقت عن OTP).', max_length=12, verbose_name='كود الدخول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'فعّال'), ('frozen', 'مجمّد'), ('expired', 'منتهي'), ('cancelled', 'ملغى')], default='active', max_length=12, verbose_name='الحالة')),
                ('frozen_at', models.DateField(blank=True, help_text='يُستخدم لتمديد تاريخ الانتهاء بشكل صحيح عند استئناف الاشتراك.', null=True, verbose_name='تاريخ التجميد')),
                ('review_requested_at', models.DateTimeField(blank=True, help_text='يمنع إرسال طلب تقييم أكثر من مرة (أمر send_review_requests).', null=True, verbose_name='تاريخ إرسال طلب التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.customer', verbose_name='العميل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
