# Generated by Django 6.1 on 2026-09-02 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='من')),
                ('end_time', models.TimeField(verbose_name='إلى')),
                ('is_booked', models.BooleanField(default=False, verbose_name='محجوز')),
            ],
            options={
                'verbose_name': 'موعد استشارة',
                'verbose_name_plural': 'مواعيد الاستشارات',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('bio_ar', models.TextField(blank=True, verbose_name='نبذة (عربي)')),
                ('bio_en', models.TextField(blank=True, verbose_name='نبذة (إنجليزي)')),
                ('specialty_ar', models.CharField(blank=True, max_length=150, verbose_name='التخصص (عربي)')),
                ('specialty_en', models.CharField(blank=True, max_length=150, verbose_name='التخصص (إنجليزي)')),
                ('photo', models.ImageField(blank=True, upload_to='nutritionists/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'أخصائي تغذية',
                'verbose_name_plural': 'أخصائيو التغذية',
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('goal_notes', models.TextField(blank=True, verbose_name='شو بتحب تناقش بالجلسة؟')),
                ('price_jod', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر (د.أ)')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكّد'), ('completed', 'تمّت'), ('cancelled', 'ملغى')], default='pending', max_length=12, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('consultations_page', 'صفحة الاستشارات'), ('calculator_upsell', 'بعد حاسبة السعرات'), ('other', 'أخرى')], default='consultations_page', max_length=30, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='consultations.consultationslot', verbose_name='الموعد')),
            ],
            options={
                'verbose_name': 'حجز استشارة',
                'verbose_name_plural': 'حجوزات الاستشارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='nutritionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='consultations.nutritionist', verbose_name='الأخصائي'),
        ),
        migrations.AlterUniqueTogether(
            name='consultationslot',
            unique_together={('nutritionist', 'date', 'start_time')},
        ),
    ]
