# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.PositiveIntegerField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'قليل الحركة (مكتب، بدون رياضة)'), ('light', 'نشاط خفيف (رياضة 1-3 أيام بالأسبوع)'), ('moderate', 'نشاط متوسط (رياضة 4-5 أيام بالأسبوع)'), ('active', 'نشيط (رياضة يومية أو مكثفة 3-4 أيام)'), ('very_active', 'نشيط جداً (رياضة مكثفة 6-7 أيام)'), ('athlete', 'رياضي محترف أو عمل بدني شاق يومياً')], max_length=20)),
                ('goal', models.CharField(choices=[('loss', 'خسارة وزن'), ('maintain', 'تثبيت الوزن'), ('gain', 'بناء عضل')], max_length=20)),
                ('result_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('result_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('result_carbs_g', models.PositiveIntegerField(blank=True, null=True)),
                ('result_fat_g', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
            ],
            options={
                'verbose_name': 'نتيجة حاسبة سعرات',
                'verbose_name_plural': 'نتائج حاسبة السعرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
