# Generated by Django 6.1 on 2026-09-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriecalculation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='caloriecalculation',
            name='progress_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, verbose_name='كود المتابعة'),
        ),
    ]
