# Generated by Django 6.1 on 2026-09-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_caloriecalculation_customer_phone_and_more'),
        ('plans', '0005_alter_deliveryarea_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriecalculation',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'قليل الحركة (مكتب، بدون رياضة)'), ('light', 'نشاط خفيف (رياضة 1-3 أيام بالأسبوع)'), ('moderate', 'نشاط متوسط (رياضة 4-5 أيام بالأسبوع)'), ('active', 'نشيط (رياضة يومية أو مكثفة 3-4 أيام)'), ('very_active', 'نشيط جداً (رياضة مكثفة 6-7 أيام)'), ('athlete', 'رياضي محترف أو عمل بدني شاق يومياً')], max_length=20, verbose_name='مستوى النشاط'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='age',
            field=models.PositiveIntegerField(verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='goal',
            field=models.CharField(choices=[('loss', 'خسارة وزن'), ('maintain', 'تثبيت الوزن'), ('gain', 'بناء عضل')], max_length=20, verbose_name='الهدف'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='height_cm',
            field=models.PositiveIntegerField(verbose_name='الطول (سم)'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='result_calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات الناتجة'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='result_carbs_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='كربوهيدرات (غ)'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='result_fat_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='دهون (غ)'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='result_protein_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بروتين (غ)'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='suggested_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='الخطة المقترحة'),
        ),
        migrations.AlterField(
            model_name='caloriecalculation',
            name='weight_kg',
            field=models.PositiveIntegerField(verbose_name='الوزن (كغ)'),
        ),
    ]
