# Generated by Django 6.1 on 2026-09-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'نوع وجبة',
                'verbose_name_plural': 'أنواع الوجبات',
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='عادة يوم الأحد')),
                ('is_active', models.BooleanField(default=True, help_text='فعّل هذا المنيو ليظهر بالموقع (يعطل تلقائياً القديم)')),
            ],
            options={
                'verbose_name': 'منيو أسبوعي',
                'verbose_name_plural': 'المنيو الأسبوعي',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')])),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.PositiveIntegerField()),
                ('carbs_g', models.PositiveIntegerField()),
                ('fat_g', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='menu/')),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtype')),
                ('weekly_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.weeklymenu')),
            ],
            options={
                'verbose_name': 'وجبة',
                'verbose_name_plural': 'الوجبات',
                'ordering': ['day_of_week'],
            },
        ),
    ]
