# Generated by Django 6.1 on 2026-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymenu',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='فعّل هذا المنيو ليظهر بالموقع (يعطل تلقائياً القديم)'),
        ),
    ]
