# Generated by Django 6.1 on 2026-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_historicalmenuitem_historicalweeklymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='typical_carbs_pct',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='كربوهيدرات %'),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='typical_fat_pct',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='دهون %'),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='typical_protein_pct',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='بروتين %'),
        ),
    ]
