# Generated by Django 6.1 on 2026-09-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_mealtype_typical_carbs_pct_mealtype_typical_fat_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='السعرات'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='carbs_g',
            field=models.PositiveIntegerField(verbose_name='كربوهيدرات (غ)'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], verbose_name='يوم الأسبوع'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='fat_g',
            field=models.PositiveIntegerField(verbose_name='دهون (غ)'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='image',
            field=models.TextField(blank=True, max_length=100, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='meal_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='menu.mealtype', verbose_name='نوع الوجبة'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='name_ar',
            field=models.CharField(max_length=120, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='protein_g',
            field=models.PositiveIntegerField(verbose_name='بروتين (غ)'),
        ),
        migrations.AlterField(
            model_name='historicalmenuitem',
            name='weekly_menu',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='menu.weeklymenu', verbose_name='المنيو الأسبوعي'),
        ),
        migrations.AlterField(
            model_name='historicalweeklymenu',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='فعّل هذا المنيو ليظهر بالموقع (يعطل تلقائياً القديم)', verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='historicalweeklymenu',
            name='week_start_date',
            field=models.DateField(help_text='عادة يوم الأحد', verbose_name='تاريخ بداية الأسبوع'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=10, verbose_name='رمز تعبيري'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name_ar',
            field=models.CharField(max_length=50, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='المُعرّف'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='السعرات'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='carbs_g',
            field=models.PositiveIntegerField(verbose_name='كربوهيدرات (غ)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'الأحد'), (1, 'الاثنين'), (2, 'الثلاثاء'), (3, 'الأربعاء'), (4, 'الخميس'), (5, 'الجمعة'), (6, 'السبت')], verbose_name='يوم الأسبوع'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='fat_g',
            field=models.PositiveIntegerField(verbose_name='دهون (غ)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='menu/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.mealtype', verbose_name='نوع الوجبة'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_ar',
            field=models.CharField(max_length=120, verbose_name='الاسم (عربي)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنجليزي)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='protein_g',
            field=models.PositiveIntegerField(verbose_name='بروتين (غ)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weekly_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.weeklymenu', verbose_name='المنيو الأسبوعي'),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='فعّل هذا المنيو ليظهر بالموقع (يعطل تلقائياً القديم)', verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='week_start_date',
            field=models.DateField(help_text='عادة يوم الأحد', verbose_name='تاريخ بداية الأسبوع'),
        ),
    ]
