# Generated by Django 6.1 on 2026-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_historicalmenuitem_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة افتراضية لكل خطط هذا النوع اللي ما إلها صورة خاصة.', null=True, upload_to='meal_types/', verbose_name='صورة افتراضية'),
        ),
    ]
